[package]
name = "serde_tag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
[dependencies]
darling = "0.20.1"
proc-macro2 = "1.0.58"
quote = "1.0.27"
serde.workspace = true
syn = { version = "2.0.16", features = ["full", "extra-traits"] }